version: '3'
services:
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        networks:
            - internal
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_VERSION:${MYSQL_VERSION}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db:/var/lib/mysql"
            - "./etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    php:
        build: ./web
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache
            - ./web/:/app
        ports:
            - '8000:80'
        restart: always
        container_name: php
        networks:
            - internal
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - mysqldb
    composer:
        image: yiisoftware/yii2-php:7.2-apache
        networks:
            - internal
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache
            - ./web/:/app
        command: "yii migrate --interactive=0"
        depends_on:
            - php
            - mysqldb
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        networks:
            - internal
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.1/24
