version: '3'
services:
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_VERSION:${MYSQL_VERSION}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db:/var/lib/mysql"
            - "./etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    php:
        build: ./web
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./web/:/app:delegated
        ports:
            - '8000:80'
        restart: always
        container_name: php
        depends_on:
            - mysqldb
    composer:
        image: yiisoftware/yii2-php:7.1-apache
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./web/:/app:delegated
        command: "yii migrate --interactive=0"
        depends_on:
            - php
            - mysqldb
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
