FROM php:7.2-fpm
RUN docker-php-ext-install pdo_mysql
#RUN  gd && cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php composer-setup.php --install-dir=/usr/local/bin --filename=composer

